language: minimal

env:
  global:
    - THIS_DOCKER_REGISTRY=superflyxxi.dlinkddns.com:5000
    - THIS_DOCKER_REPO=superflyxxi
    - THIS_DOCKER_LABEL=${TRAVIS_BRANCH}

before_script:
  - sudo apt-get install -y jq
  - sudo service docker stop
  - sudo ls -lha /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json | jq ". + {\"insecure-registries\":[\"${THIS_DOCKER_REGISTRY}\"] }"
  - sudo bash -c "jq \". + {\\\"insecure-registries\\\":[\\\"${THIS_DOCKER_REGISTRY}\\\"] }\" /etc/docker/daemon.json" 
#  - sudo bash -c "jq \". + {\\\"insecure-registries\\\":[\\\"${THIS_DOCKER_REGISTRY}\\\"] }\" /etc/docker/daemon.json > /etc/docker/daemon.json" 
  - sudo jq ". + {\"insecure-registries\":[\"${THIS_DOCKER_REGISTRY}\"] }" /etc/docker/daemon.json
#  - sudo jq ". + {\"insecure-registries\":[\"${THIS_DOCKER_REGISTRY}\"] }" /etc/docker/daemon.json | sudo tee /etc/docker/daemon.json
#  - sudo cat /etc/docker/daemon.json | jq ". + {\"insecure-registries\":[\"${THIS_DOCKER_REGISTRY}\"] }" | sudo tee /etc/docker/daemon.json
  - sudo ls -lha /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json
# Download cert from this registry
  - sudo mkdir -p "/etc/docker/certs.d/${THIS_DOCKER_REGISTRY}"
  - openssl s_client -showcerts -connect ${THIS_DOCKER_REGISTRY} < /dev/null 2> /dev/null | openssl x509 -outform PEM | sudo tee "/etc/docker/certs.d/${THIS_DOCKER_REGISTRY}/ca.crt"
  - sudo service docker start
  - echo ${THIS_DOCKER_REGISTRY_PASSWORD} | docker login --username ${THIS_DOCKER_REGISTRY_USERNAME} --password-stdin ${THIS_DOCKER_REGISTRY}

script:
  - docker build -t httpd-cron:build .

after_success:
  - docker tag httpd-cron:build ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/httpd-cron:${THIS_DOCKER_LABEL}
  - docker push ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/httpd-cron:${THIS_DOCKER_LABEL}
  - if [[ ! -z "${TRAVIS_TAG}" ]]; then
        docker tag httpd-cron:build ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/httpd-cron:latest;
        docker push ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/httpd-cron:latest;
    fi

