# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
    docker: circleci/docker@1.5.0

# Orchestrate or schedule a set of jobs
jobs:
  build:
    environment:
      THIS_DOCKER_REPO: superflyxxi
      THIS_DOCKER_IMAGE: httpd-cron
      
    machine: true
    steps:
      - run:
          name: Custom enviroment variables
          command: |
            echo 'export THIS_DOCKER_LABEL=${CIRCLE_BRANCH}' >> ${BASH_ENV}
            if [[ ! "${CIRCLE_BRANCH}" == "master" ]] && [[ ! ${CIRCLE_BRANCH} == v* ]]; then
              echo 'export CACHE_FROM_IMAGE=${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/${THIS_DOCKER_IMAGE}:master' >> ${BASH_ENV}
            fi
            cat ${BASH_ENV}
      - docker/check:
          docker-username: THIS_DOCKER_REGISTRY_USERNAME
          docker-password: THIS_DOCKER_REGISTRY_PASSWORD
          registry: $THIS_DOCKER_REGISTRY
      - docker/pull:
          images: httpd:alpine,${CACHE_FROM_IMAGE}
          ignore-docker-pull-error: true
      - checkout
      - docker/build:
          docker-context: src/
          path: src/
          image: ${THIS_DOCKER_REPO}/${THIS_DOCKER_IMAGE}
          tag: ${THIS_DOCKER_LABEL}
          registry: ${THIS_DOCKER_REGISTRY}
          extra_build_args: --build-arg BUILD_IMAGE=${THIS_REGISTRY}/${THIS_IMAGE}:${THIS_LABEL}a
          cache_from: ${CACHE_FROM_IMAGE}
          step-name: Build docker image
      - run:
          name: Run tests
          command: |
            cd tests/
            TEST_IMAGE=${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/${THIS_DOCKER_IMAGE}:${THIS_LABEL} ./runTests.sh
      #- store_test_results:
          #path: testResults
      #- store_artifacts:
          #path: testResults
      - docker/push:
          step-name: Pushing actual image
          registry: $THIS_DOCKER_REGISTRY
          image: ${THIS_DOCKER_REPO}/${THIS_DOCKER_IMAGE}
          tag: ${THIS_THIS_LABEL}

workflows:
  default:
    jobs:
      - build
