# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
    docker: circleci/docker@1
    node: circleci/node@4

jobs:
# Orchestrate or schedule a set of jobs
  build-test-push:
    environment:
      THIS_DOCKER_IMAGE: httpd-cron
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Custom enviroment variables
          command: |
            echo 'export THIS_DOCKER_LABEL=$(cat /tmp/workspace/version.txt)' >> ${BASH_ENV}
            cat ${BASH_ENV}
      - docker/check:
          registry: $DOCKER_REGISTRY
      - checkout
      - docker/build:
          docker-context: src/
          path: src/
          image: ${THIS_DOCKER_IMAGE}
          tag: ${THIS_DOCKER_LABEL}
          registry: ${DOCKER_REGISTRY}
          extra_build_args: --build-arg BUILD_IMAGE=${THIS_REGISTRY}/${THIS_IMAGE}:${THIS_DOCKER_LABEL}
          step-name: Build docker image
      - run:
          name: Run tests
          command: |
            cd tests/
            sudo chown root:root crontab
            TEST_IMAGE=${DOCKER_REGISTRY}/${THIS_DOCKER_IMAGE}:${THIS_DOCKER_LABEL} ./runTests.sh
      - run: 
          name: Determine docker tags to push
          command: |
            export PUSH_DOCKER_TAGS=${THIS_DOCKER_LABEL}
            if [[ "main" == "<< pipeline.git.branch >>" ]] && [[ "main" != "${THIS_DOCKER_LABEL}" ]]; then
              for A in $(echo ${THIS_DOCKER_LABEL} | tr "." "\n"); do 
                NOW="$PREV.$A"
                docker tag ${DOCKER_REGISTRY}/${THIS_DOCKER_IMAGE}:${THIS_DOCKER_LABEL} ${DOCKER_REGISTRY}/${THIS_DOCKER_IMAGE}:${NOW:1}
                export PUSH_DOCKER_TAGS="${PUSH_DOCKER_TAGS},${NOW:1}"
                PREV=$NOW
              done
              docker tag ${DOCKER_REGISTRY}/${THIS_DOCKER_IMAGE}:${THIS_DOCKER_LABEL} ${DOCKER_REGISTRY}/${THIS_DOCKER_IMAGE}:latest
              export PUSH_DOCKER_TAGS="${PUSH_DOCKER_TAGS},latest"
            fi
            echo "Docker tags: ${PUSH_DOCKER_TAGS}"
            echo "export PUSH_DOCKER_TAGS=${PUSH_DOCKER_TAGS}" >> ${BASH_ENV}
      - docker/push:
          step-name: Pushing images
          registry: $DOCKER_REGISTRY
          image: ${THIS_DOCKER_IMAGE}
          tag: ${PUSH_DOCKER_TAGS}

  release:
    parameters:
      prerelease:
        description: Whether it's a pre-release and not actually release.
        type: boolean
        default: false
    executor: node/default
    steps:
      - checkout
      - run: 
          name: Check for package.json
          command: |
            if [[ ! -f package.json ]]; then npm init -y; fi
      - run: 
          name: Add semenatic-release/exec to package.json
          command: |
            npm install -D @semantic-release/exec
      - when:
          condition: << parameters.prerelease >>
          steps:
            run:
              name: Define additional args
              command: |
                echo "ADDITIONAL_ARGS=--dry-run" >> ${BASH_ENV}
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run semantic-release
          command: |
            npx semantic-release ${ADDITIONAL_ARGS}
            if [[ -f version.txt ]]; then 
              cp -v version.txt /tmp/workspace
            else 
              echo "${CIRCLE_BRANCH}" | sed 's#/#-#g' > /tmp/workspace/version.txt
            fi
            echo "Version: $(cat /tmp/workspace/version.txt)"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - version.txt

workflows:
  default:
    jobs:
      - release:
          name: pre-release
          context: default
          prerelease: true
      - build-test-push:
          context: default
          requires:
            - pre-release
      - release:
          name: release
          context: default
          prerelease: false
          requires:
            - build-test-push
