# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
    docker: circleci/docker@2
    node: circleci/node@5

anchors:
  node-executor: &node-executor
    name: node/default
    tag: '16.14'
  docker-executor: &docker-executor
    name: docker/machine
    dlc: false

jobs:
# Orchestrate or schedule a set of jobs
  build-test-push:
    environment:
      THIS_DOCKER_IMAGE: httpd-cron
    executor: *docker-exectur
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Custom enviroment variables
          command: |
            export THIS_DOCKER_TAG=$(cat /tmp/workspace/version.txt)
            echo "export THIS_DOCKER_TAG=${THIS_DOCKER_TAG}" >> ${BASH_ENV}
            export CACHE_FROM_IMAGES=$(grep "^FROM " src/Dockerfile | sed 's/FROM //g')
            if [[ "<< pipeline.git.branch >>" != "main" ]]; then
              export CACHE_FROM_IMAGES="${CACHE_FROM_IMAGES},${DOCKER_REGISTRY}/${THIS_DOCKER_IMAGE}:latest"
            fi
            echo "export CACHE_FROM_IMAGES=${CACHE_FROM_IMAGES}" >> ${BASH_ENV}
            export DOCKER_TAGS=${THIS_DOCKER_TAG}
            if [[ "main" == "<< pipeline.git.branch >>" ]] && [[ "main" != "${THIS_DOCKER_TAG}" ]]; then
              for A in $(echo ${THIS_DOCKER_TAG} | tr "." "\n"); do 
                NOW="$PREV.$A"
                export DOCKER_TAGS="${DOCKER_TAGS},${NOW:1}"
                PREV=$NOW
              done
              export DOCKER_TAGS="${DOCKER_TAGS},latest"
            fi
            echo "export DOCKER_TAGS=${DOCKER_TAGS}" >> ${BASH_ENV}
            cat ${BASH_ENV}
      - docker/check:
          registry: $DOCKER_REGISTRY
      - docker/build:
          docker-context: src/
          path: src/
          image: ${THIS_DOCKER_IMAGE}
          tag: ${DOCKER_TAGS}
          registry: ${DOCKER_REGISTRY}
          cache_from: ${CACHE_FROM_IMAGES}
          step-name: Build docker image
      - run:
          name: Run tests
          command: |
            cd tests/
            sudo chown root:root crontab
            TEST_IMAGE=${DOCKER_REGISTRY}/${THIS_DOCKER_IMAGE}:${THIS_DOCKER_TAG} ./runTests.sh
      - run:
          name: Tag images for public repos
          command: |
            
      - docker/push:
          step-name: Pushing images to private registry
          registry: $DOCKER_REGISTRY
          image: ${THIS_DOCKER_IMAGE}
          tag: ${DOCKER_TAGS}

  release:
    parameters:
      prerelease:
        description: Whether it's a pre-release and not actually release.
        type: boolean
        default: false
    executor: *node-executor
    steps:
      - checkout
      - when:
          condition: << parameters.prerelease >>
          steps:
            run:
              name: Define additional args
              command: |
                echo "ADDITIONAL_ARGS=--dry-run" >> ${BASH_ENV}
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run semantic-release
          command: |
            npx -p semantic-release -p semantic-release/exec semantic-release ${ADDITIONAL_ARGS}
            if [[ -f version.txt ]]; then 
              cp -v version.txt /tmp/workspace
            else 
              echo "${CIRCLE_BRANCH}" | sed 's#/#-#g' > /tmp/workspace/version.txt
            fi
            echo "Version: $(cat /tmp/workspace/version.txt)"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - version.txt

workflows:
  default:
    jobs:
      - release:
          name: pre-release
          context: default
          prerelease: true
      - build-test-push:
          context: default
          requires:
            - pre-release
      - release:
          name: release
          context: default
          prerelease: false
          requires:
            - build-test-push
